name: ffuf-subdomain
#https://github.com/ayadim/ffuf-action
on:
    workflow_dispatch:

jobs:
  ffuf-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: FFUF - Subdomain fuzzer
        uses: ayadim/ffuf-action@main
        with:
          config: config/ffuf-vhost.ini
          wordlist: wordlist/subdomains/OneListForAll/subdomains_short.txt

      - name: GitHub Workflow artifacts
        uses: actions/upload-artifact@v2
        with:
          name: hespress-result
          path: ffuf-result.md