name: gau
#https://github.com/ayadim/gau-action
on:
    workflow_dispatch:

jobs:
  gau-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: 💥 gau - archive crawler
        uses: ayadim/gau-action@main
        with:
          urls: input-data/gau-domains.txt
          threads: 10

      - name: GitHub Workflow artifacts
        uses: actions/upload-artifact@v2
        with:
          name: gau.log
          path: gau.log