name: subfinder
#https://github.com/projectdiscovery/subfinder-action
on:
    workflow_dispatch:

jobs:
  subfinder-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: SubFinder - DNS Enumeration
        uses: projectdiscovery/subfinder-action@main
        with:
          list: input-data/subfinder-domains.txt
          config: config/subfinder-config.yaml

      - name: GitHub Workflow artifacts
        uses: actions/upload-artifact@v2
        with:
          name: subfinder.log
          path: subfinder.log